pre-commit:
  commands:
    'prettier:fix':
      glob: '*.{html,css,less,scss,sass,js,ts,jsx,tsx,vue,json,yaml,yml,md,mdx}'
      run: 'npm run format:lefthook {staged_files}'
      stage_fixed: true
